Check Health (#42)

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -86,6 +86,20 @@ jobs:
     environment: staging
     runs-on: ubuntu-latest
     steps:
+    - name: Checkout code
+      uses: actions/checkout@v4
+
+    - name: Run Health Check
+      id: health_check
+      run: |
+        chmod +x check-health.sh
+        ./check-health.sh "{{ vars.NEXT_PUBLIC_APP_API_URL }}" "{{ vars.NEXT_PUBLIC_APP_URL }}" "{{ vars.NEXT_PUBLIC_APP_SOCKET_URL }}" | tee health_check_output.txt
+
+    - name: Save Health Check Output to Step Summary
+      if: success() || failure() # always run even if the previous step fails
+      run: |
+        cat health_check_output.txt >> $GITHUB_STEP_SUMMARY
+
     - name: Run Integration Tests in QA
       run: |
         echo "Integration tests to be added here..."
