Tests Passed Flag (#46)
* Force backend tests to fail

* fix: update PostMovieViewTest to expect HTTP 400 response

* fix: update CI/CD workflows to handle test failures and adjust PostMovieViewTest assertions

* chore: bump version numbers for backend and socket to 1.1.7 and 0.8.7 respectively

* fix: update PostMovieViewTest to assert HTTP 400 response instead of 200

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -51,10 +51,16 @@ jobs:
   check-tests:
     name: Tests Passed Flag
     needs: unit-tests
+    if: success() || failure()
     runs-on: ubuntu-latest
     steps:
-      - name: Check all tests passed
-        run: echo "All unit tests passed!"
+      - name: Verify if all unit tests passed
+        run: |
+          if [ "${{ needs.unit-tests.result }}" != "success" ]; then
+            echo "Some unit tests failed. Marking check-tests as failed."
+            exit 1
+          fi
+          echo "All unit tests passed successfully!"
 
   build-and-publish-images:
     name: Build and Push to ACR - ${{ matrix.service }} 
