Test Summary (JUnit) (#41)
* Test Summary (JUnit)

* fix working directory

* fix path in Test Summary

* Testing with another reporter

* testing report when a test fails

* add check permissions

* fixing permissions

* testing parameters junit report

* set annotation_only to true

* coverage report

* add coverage report to job summary

* fix collect coverage from

* fix coverage report

* frontend tests

* comment line for testing

* changed sonar coverage report path

diff --git a/.github/workflows/unit-tests.yml b/.github/workflows/unit-tests.yml
--- a/.github/workflows/unit-tests.yml
+++ b/.github/workflows/unit-tests.yml
@@ -10,6 +10,8 @@ on:
 jobs:
   unit-tests:
     runs-on: ubuntu-latest
+    permissions:
+        checks: write
     steps:
     - uses: actions/checkout@v4
 
@@ -26,10 +28,9 @@ jobs:
       run: |
         python -m pip install --upgrade pip
         pip install -r requirements.txt
-        pip install coverage
-        coverage run --omit='**/migrations/*' --omit='**/tests.py' --omit='**/admin.py' manage.py test apps
-        coverage report --format=markdown >> $GITHUB_STEP_SUMMARY
-        coverage xml
+        pip install coverage unittest-xml-reporting
+        coverage run --omit='**/migrations/*' --omit='**/tests.py' --omit='**/admin.py' manage.py test apps --testrunner=xmlrunner.extra.djangotestrunner.XMLTestRunner
+        coverage xml -o coverage/cobertura-coverage.xml
 
     - name: Set up Node.js
       if: ${{ inputs.service != 'backend' }}
@@ -45,6 +46,30 @@ jobs:
         npm install
         npm run build --if-present
         npm run test --if-present
+
+    - name: Publish Test Report
+      uses: mikepenz/action-junit-report@v5
+      if: success() || failure() # always run even if the previous step fails
+      with:
+        report_paths: '${{ inputs.service }}/TEST-*.xml'
+        annotate_only: true
+
+    - name: Code Coverage Report
+      uses: irongut/CodeCoverageSummary@v1.3.0
+      if: success() || failure() # always run even if the previous step fails
+      with:
+        filename: ${{ inputs.service }}/coverage/cobertura-coverage.xml
+        badge: true
+        format: markdown
+        # hide_branch_rate: false
+        # hide_complexity: true
+        indicators: true
+        output: both
+
+    - name: Add Code Coverage to Job Summary
+      if: success() || failure() # always run even if the previous step fails
+      run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
+
 
     - name: SonarCloud Scan
       uses: SonarSource/sonarcloud-github-action@master
